[project]
name        = "dearlog"
description = "🪵 A Human Logging Library"
version     = "0.1.1"
license     = "MIT"
readme      = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "attrs",
    "rich",
]

[project.urls]
GitHub = "https://github.com/BrokenSource/DearLog"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
