[project]
site_name = "DearLog"
site_description = "🪵 A Human Logging Library"
site_author = "Tremeschin"
site_url  = "https://dearlog.tremeschin.com/"
repo_url  = "https://github.com/BrokenSource/DearLog/"
repo_name = "BrokenSource/DearLog"
copyright = "&copy; CC BY-SA 4.0, <a href='https://github.com/Tremeschin/'>Tremeschin</a> 🇧🇷"
docs_dir  = "website"
nav = [
  {Origin = "https://tremeschin.com/"},
  {"Home" = [
    "index.md",
    "about/changelog.md",
  ]},
  {"Documentation" = [
    "docs/index.md",
    "docs/levels.md",
    "docs/handlers.md",
  ]},
]

[project.theme]
name = "zentheme"
favicon = "assets/images/logo.png"

[project.theme.icon]
logo = "octicons/log-16"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"
